export const listOfItems = [
  {
    name: "Coca-cola",
    price: "8",
    id: "cc",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/cc.png',
  }, 
  {
    name: "Pepsi Max",
    price: "8",
    id: "pm",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/pm.png',
  },
  {
    name: "7up",
    price: "8",
    id: "su",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/su.png',
  }, 
  {
    name: "Zingo",
    price: "8",
    id: "z",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/z.png',
  },{
    name: "Trocadero",
    price: "8",
    id: "tr",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/tr.png',
  }, 
  {
    name: "Loka Citron",
    price: "8",
    id: "lc",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/lc.png',
  },
  {
    name: "Loka Päron",
    price: "8",
    id: "lp",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/lp.png',
  }, 
  {
    name: "Celsius Citron",
    price: "20",
    id: "cc",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/cel.png',
  },
  {
    name: "Nocco Miami",
    price: "20",
    id: "nm",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/nm.png',
  }, 
  {
    name: "Nocco Caribbean",
    price: "20",
    id: "nc",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/nc.png',
  },
  {
    name: "Froosh Mango & Apelsin",
    price: "20",
    id: "fm",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/fm.png',
  }, 
  {
    name: "Froosh Blåbär & Hallon",
    price: "20",
    id: "fb",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/fb.png',
  },{
    name: "Pucko",
    price: "12",
    id: "pu",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/pu.png',
  }, 
  {
    name: "Billy's original",
    price: "14",
    id: "bo",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bo.png',
  },
  {
    name: "Billy's veggie",
    price: "14",
    id: "bv",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bv.png',
  }, 
  {
    name: "Gorby's",
    price: "14",
    id: "g",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/g.png',
  },
  {
    name: "Wasa Sourcream&Onion",
    price: "10",
    id: "ws",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/ws.png',
  }, 
  {
    name: "Wasa Tomat&Basil",
    price: "10",
    id: "wt",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/wt.png',
  },
  {
    name: "Wasa Cheese&Paprika",
    price: "10",
    id: "wp",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/wp.png',
  }, 
  {
    name: "Wasa French Herbs",
    price: "10",
    id: "wf",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/wf.png',
  },
  {
    name: "Risifrutti Hallon",
    price: "10",
    id: "rh",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/rh.png',
  },
  {
    name: "Risifrutti Jordgubb",
    price: "10",
    id: "rj",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/rj.png',
  },
  {
    name: "Barebells Peanut",
    price: "22",
    id: "bp",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bp.png',
  },{
    name: "Barebells Bluberry&cheesecake",
    price: "22",
    id: "bb",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bb.png',
  }, 
  {
    name: "Barebells Caramel&Cashew",
    price: "22",
    id: "bc",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bc.png',
  },
  {
    name: "Barebells White Chocolate",
    price: "22",
    id: "bw",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/bw.png',
  }, 
  {
    name: "Kexchoklad",
    price: "7",
    id: "k",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/k.png',
  },{
    name: "Daim",
    price: "5",
    id: "d",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/d.png',
  }, 
  {
    name: "Twix",
    price: "7",
    id: "tw",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/tw.png',
  },
  {
    name: "Snickers",
    price: "7",
    id: "s",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/s.png',
  }, 
  {
    name: "Pringles Original",
    price: "9",
    id: "po",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/po.png',
  },
  {
    name: "Pringles Sourcream",
    price: "9",
    id: "ps",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/ps.png',
  },{
    name: "Pringles Paprika",
    price: "9",
    id: "pp",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/pp.png',
  }, 
  {
    name: "Nappar Sour",
    price: "7",
    id: "ns",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/ns.png',
  },
  {
    name: "Nappar Cola",
    price: "7",
    id: "nco",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/nco.png',
  }, 
  {
    name: "Nappar Fruit",
    price: "7",
    id: "nf",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/nf.png',
  },{
    name: "Nappar Lakrits",
    price: "7",
    id: "nl",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/nl.png',
  }, 
  {
    name: "Delicatoboll blå",
    price: "6",
    id: "db",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/db.png',
  },
  {
    name: "Delicatoboll gul",
    price: "6",
    id: "dg",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/dg.png',
  }, 
  {
    name: "Kanelbulle",
    price: "6",
    id: "ka",
    img: 'https://fryn4538.github.io/Skrubben-Pay/img/ka.png',
  }

];
